global:
  scrape_interval: 3s
  #evaluation_interval: 15s

rule_files:
  # - "first_rules" 
  # - "secound_rules" 

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          grupo: 'prometheus'

  - job_name: app
    static_configs:
      - targets: ['app:5000']
        labels:
          grupo: 'app'
